// lib/models.ts
//
// Centralized, verified registry of AI models supported by Promptea's analyzer.
//
// v1.2.0: every entry now carries an explicit lifecycle status, the date it was
// verified against primary sources, and the source URL used. UI selectors only
// offer entries with `selectable: true`; legacy/deprecated entries are retained
// (non-selectable) for compatibility with older links, telemetry, and SEO pages.
//
// v1.3.0: selectable stable/preview entries additionally carry structured
// `capabilities` data and `interactionProfiles` consumed by the deterministic
// matcher.
//
// v1.6.0: full provider sweep on 2026-09-24 against first-party docs only
// (OpenAI, Anthropic, Google, xAI, DeepSeek, Moonshot/Kimi, Perplexity). Every
// selectable entry now also names a `promptProfile` — the provider's current
// prompting guidance, consumed by the deterministic shaper and the adaptive
// refiner (lib/engine/modelProfiles.ts) so each model gets a genuinely
// different prompt, not just a different label.
//
// Promptea OPTIMIZES prompts for these models — it does not execute them.
//
// Maintenance policy:
// 1. Verify IDs only against official provider documentation (see sourceUrl).
// 2. Never add a model from a blog post, social post, or memory.
// 3. Update `verifiedAt` whenever an entry is re-checked.
// 4. Exactly one `defaultForTarget: true` entry per target (enforced by tests).
// 5. When a model is superseded, set status + replacementId instead of deleting.

import type { InteractionProfile, Lang, MatchCategory, PromptProfileId, TargetAI } from "@/lib/domain";
import { TARGETS } from "@/lib/domain";

export type ModelProvider =
  | "openai"
  | "anthropic"
  | "google"
  | "xai"
  | "deepseek"
  | "perplexity"
  | "moonshot"
  | "meta"
  | "mistral";

export type ModelStatus = "stable" | "preview" | "legacy" | "deprecated";

export type ModelStrength =
  | "reasoning"
  | "coding"
  | "writing"
  | "data"
  | "multimodal"
  | "long_context"
  | "speed"
  | "creativity"
  | "search";

export type Modality = "text" | "image" | "audio" | "video" | "pdf";

export type LatencyClass = "fast" | "balanced" | "slow";

/** 0 = wrong tool … 3 = among the best market choices for the category. */
export type FitScore = 0 | 1 | 2 | 3;

export type TaskFitScores = Partial<Record<MatchCategory, FitScore>>;

/**
 * v1.3.0 structured capability data consumed by the deterministic matcher
 * (lib/matcher). Values must come from official provider documentation —
 * same maintenance policy as the rest of the entry.
 */
export type ModelCapabilities = {
  inputModalities: Modality[];
  outputModalities: Modality[];
  contextWindowTokens: number | null;
  maxOutputTokens: number | null;
  latencyClass: LatencyClass;
  /** Native JSON/structured-output mode. */
  structuredOutput: boolean;
  toolUse: boolean;
  /** Built-in web search/grounding with citations. */
  nativeSearch: boolean;
  /** 0 none, 1 basic, 2 strong, 3 frontier deliberate reasoning. */
  reasoningTier: FitScore;
  /** Suitability inside repository coding agents (Claude Code, Codex…). */
  codingAgentFit: FitScore;
  taskFit: TaskFitScores;
  /** Model-specific prompting advice, shown in matcher adaptation tips. */
  promptGuidance: { es: string; en: string };
};

export type ModelEntry = {
  /** Stable internal id (also used in URLs/telemetry — do not rename). */
  id: string;
  /** Display name in the UI. */
  label: string;
  provider: ModelProvider;
  target: TargetAI;
  family: string;
  status: ModelStatus;
  strengths: ModelStrength[];
  notes: { es: string; en: string };
  /** Exact model id in the provider's API, when it differs from `id`. */
  apiModelId?: string;
  openRouterId?: string;
  /** ISO date this entry was last verified against `sourceUrl`. */
  verifiedAt: string;
  /** Primary source used for verification. */
  sourceUrl: string;
  /** Suggested replacement when status is legacy/deprecated. */
  replacementId?: string;
  /** Whether the model can be chosen in the UI selector. */
  selectable: boolean;
  /** Exactly one per target (validated by tests). */
  defaultForTarget?: boolean;
  /** v1.3.0 matcher data. Required on selectable stable/preview entries. */
  capabilities?: ModelCapabilities;
  /** Interaction environments this model powers (chat, coding agent, …). */
  interactionProfiles?: InteractionProfile[];
  /** v1.6.0 prompting profile. Required on selectable entries (test-enforced). */
  promptProfile?: PromptProfileId;
};

/** 2026-09-24 research sweep: every provider-backed entry re-verified. */
const VERIFIED = "2026-09-24";
/** Earlier sweep — kept for entries outside the 2026-09-24 research pass. */
const VERIFIED_PREV = "2026-07-12";

const SRC = {
  openai: "https://developers.openai.com/api/docs/models",
  anthropic: "https://platform.claude.com/docs/en/models/overview",
  google: "https://ai.google.dev/gemini-api/docs/models",
  xai: "https://docs.x.ai/developers/models",
  deepseek: "https://api-docs.deepseek.com/quick_start/pricing",
  moonshot: "https://platform.kimi.ai/docs/models",
  perplexity: "https://docs.perplexity.ai/docs/agent-api/presets",
  perplexitySonar: "https://docs.perplexity.ai/docs/sonar/models",
} as const;

export const MODEL_REGISTRY: ModelEntry[] = [
  // ── OpenAI ────────────────────────────────────────────────────────────────
  {
    id: "gpt-6-astra",
    label: "GPT-6 Astra",
    provider: "openai",
    target: "gpt",
    family: "GPT",
    status: "stable",
    strengths: ["reasoning", "coding", "writing", "long_context", "multimodal"],
    notes: {
      es: "El modelo más capaz de OpenAI (GPT-6, sep 2026) para el trabajo de punta a punta más difícil. Necesita menos instrucciones paso a paso que los GPT anteriores: dale objetivo, restricciones y permisos, y dejalo llevar la tarea hasta el final.",
      en: "OpenAI's most capable model (GPT-6, Sep 2026) for the hardest end-to-end work. It needs less step-by-step instruction than earlier GPTs: give it the goal, constraints, and permissions, and let it carry the task through.",
    },
    apiModelId: "gpt-6-astra",
    verifiedAt: VERIFIED,
    sourceUrl: "https://developers.openai.com/api/docs/models/gpt-6-astra",
    selectable: true,
    defaultForTarget: true,
    capabilities: {
      inputModalities: ["text", "image"],
      outputModalities: ["text"],
      contextWindowTokens: 1050000,
      maxOutputTokens: 128000,
      latencyClass: "slow",
      structuredOutput: true,
      toolUse: true,
      nativeSearch: true,
      reasoningTier: 3,
      codingAgentFit: 3,
      taskFit: {
        chat: 2,
        coding: 3,
        codingAgent: 3,
        research: 3,
        longContext: 3,
        multimodal: 2,
        dataExtraction: 3,
        creativeWriting: 2,
        marketing: 2,
        translation: 2,
        summarization: 2,
        tutoring: 3,
        imagePrompts: 2,
        complexReasoning: 3,
        fastLightweight: 0,
      },
      promptGuidance: {
        es: "Preferí objetivo y restricciones a listas de pasos: la guía demasiado específica ahora empeora los resultados. Pedile que tienda a la acción y termine la tarea, dale permisos explícitos (correr tests y arreglar fallas sin preguntar) y pedí prosa si no querés listas. No tiene esfuerzo 'none': usá 'low' como mínimo.",
        en: "Prefer the goal and constraints over step lists — overly specific guidance now hurts results. Tell it to bias toward action and finish the task, grant explicit permissions (run tests and fix failures without asking), and ask for prose if you don't want lists. It has no 'none' effort: use 'low' as the floor.",
      },
    },
    interactionProfiles: ["chat", "codingAgent"],
    promptProfile: "gpt-autonomous",
  },
  {
    id: "gpt-6-sol",
    label: "GPT-6 Sol",
    provider: "openai",
    target: "gpt",
    family: "GPT",
    status: "stable",
    strengths: ["reasoning", "coding", "writing", "long_context"],
    notes: {
      es: "El GPT-6 balanceado entre inteligencia y costo, pensado para coding complejo y flujos agénticos. Rinde mejor con prompts ajustados: pasos explícitos y formato exacto.",
      en: "The GPT-6 model that balances intelligence and cost, built for complex coding and agentic workflows. Performs best with tighter prompts: explicit steps and an exact format.",
    },
    apiModelId: "gpt-6-sol",
    verifiedAt: VERIFIED,
    sourceUrl: "https://developers.openai.com/api/docs/models/gpt-6-sol",
    selectable: true,
    capabilities: {
      inputModalities: ["text", "image"],
      outputModalities: ["text"],
      contextWindowTokens: 1050000,
      maxOutputTokens: 128000,
      latencyClass: "balanced",
      structuredOutput: true,
      toolUse: true,
      nativeSearch: true,
      reasoningTier: 2,
      codingAgentFit: 3,
      taskFit: {
        chat: 3,
        coding: 3,
        codingAgent: 3,
        research: 2,
        longContext: 3,
        multimodal: 2,
        dataExtraction: 3,
        creativeWriting: 2,
        marketing: 2,
        translation: 2,
        summarization: 3,
        tutoring: 2,
        imagePrompts: 2,
        complexReasoning: 2,
        fastLightweight: 1,
      },
      promptGuidance: {
        es: "Usá prompts más ajustados que para Astra: pasos explícitos, formato de salida exacto y largo definido, cada instrucción una sola vez. El esfuerzo de razonamiento arranca en medio (default).",
        en: "Use tighter prompts than for Astra: explicit steps, an exact output format, and a defined length, each instruction stated once. Reasoning effort starts at medium (the default).",
      },
    },
    interactionProfiles: ["chat", "codingAgent"],
    promptProfile: "gpt-guided",
  },
  {
    id: "gpt-6-luna",
    label: "GPT-6 Luna",
    provider: "openai",
    target: "gpt",
    family: "GPT",
    status: "stable",
    strengths: ["speed", "writing"],
    notes: {
      es: "El GPT-6 más eficiente, para tareas acotadas y de alto volumen. Conviene dar pasos cortos y un ejemplo del resultado esperado.",
      en: "The most efficient GPT-6 model, for focused, high-volume tasks. Prefer short, ordered steps and one example of the expected result.",
    },
    apiModelId: "gpt-6-luna",
    verifiedAt: VERIFIED,
    sourceUrl: "https://developers.openai.com/api/docs/models/gpt-6-luna",
    selectable: true,
    capabilities: {
      inputModalities: ["text", "image"],
      outputModalities: ["text"],
      contextWindowTokens: 1050000,
      maxOutputTokens: 128000,
      latencyClass: "fast",
      structuredOutput: true,
      toolUse: true,
      nativeSearch: true,
      reasoningTier: 1,
      codingAgentFit: 1,
      taskFit: {
        chat: 2,
        coding: 1,
        codingAgent: 1,
        research: 1,
        longContext: 2,
        multimodal: 1,
        dataExtraction: 2,
        creativeWriting: 1,
        marketing: 2,
        translation: 2,
        summarization: 2,
        tutoring: 1,
        imagePrompts: 1,
        complexReasoning: 1,
        fastLightweight: 3,
      },
      promptGuidance: {
        es: "Mantené el prompt compacto: pasos cortos y ordenados, un ejemplo del resultado esperado y formato de salida explícito. Para tareas realmente difíciles, escalá a Sol o Astra en vez de subirle el esfuerzo a Luna.",
        en: "Keep prompts compact: short ordered steps, one example of the expected result, and an explicit output format. For genuinely hard tasks escalate to Sol or Astra rather than raising Luna's effort.",
      },
    },
    interactionProfiles: ["chat"],
    promptProfile: "gpt-guided",
  },
  {
    id: "gpt-5.6",
    label: "GPT-5.6 (Sol)",
    provider: "openai",
    target: "gpt",
    family: "GPT",
    status: "legacy",
    strengths: ["reasoning", "coding", "writing", "long_context", "multimodal"],
    notes: {
      es: "Generación anterior (GPT-5.6 Sol, todavía disponible en la API). Promptea ahora optimiza para GPT-6 Sol.",
      en: "Previous generation (GPT-5.6 Sol, still served by the API). Promptea now optimizes for GPT-6 Sol.",
    },
    apiModelId: "gpt-5.6-sol",
    verifiedAt: VERIFIED,
    sourceUrl: SRC.openai,
    replacementId: "gpt-6-sol",
    selectable: false,
  },
  {
    id: "gpt-5.6-terra",
    label: "GPT-5.6 Terra",
    provider: "openai",
    target: "gpt",
    family: "GPT",
    status: "legacy",
    strengths: ["reasoning", "coding", "speed"],
    notes: {
      es: "Generación anterior (todavía disponible en la API). Su lugar de balance costo/inteligencia lo toma GPT-6 Sol.",
      en: "Previous generation (still served by the API). Its cost/intelligence balance slot is now GPT-6 Sol.",
    },
    apiModelId: "gpt-5.6-terra",
    verifiedAt: VERIFIED,
    sourceUrl: SRC.openai,
    replacementId: "gpt-6-sol",
    selectable: false,
  },
  {
    id: "gpt-5.6-luna",
    label: "GPT-5.6 Luna",
    provider: "openai",
    target: "gpt",
    family: "GPT",
    status: "legacy",
    strengths: ["speed", "writing"],
    notes: {
      es: "Generación anterior (todavía disponible en la API). Usá GPT-6 Luna.",
      en: "Previous generation (still served by the API). Use GPT-6 Luna.",
    },
    apiModelId: "gpt-5.6-luna",
    verifiedAt: VERIFIED,
    sourceUrl: SRC.openai,
    replacementId: "gpt-6-luna",
    selectable: false,
  },
  {
    id: "gpt-5.5",
    label: "GPT-5.5",
    provider: "openai",
    target: "gpt",
    family: "GPT",
    status: "legacy",
    strengths: ["reasoning", "coding", "writing", "long_context"],
    notes: {
      es: "Generación anterior de GPT. Considerá GPT-6 Astra para mejores resultados.",
      en: "Previous GPT generation. Consider GPT-6 Astra for better results.",
    },
    verifiedAt: VERIFIED,
    sourceUrl: SRC.openai,
    replacementId: "gpt-6-astra",
    selectable: false,
  },
  {
    id: "gpt-5.5-pro",
    label: "GPT-5.5 Pro",
    provider: "openai",
    target: "gpt",
    family: "GPT",
    status: "legacy",
    strengths: ["reasoning", "coding", "data", "long_context"],
    notes: {
      es: "Generación anterior de GPT (Pro). Considerá GPT-6 Astra para mejores resultados.",
      en: "Previous GPT generation (Pro). Consider GPT-6 Astra for better results.",
    },
    verifiedAt: VERIFIED,
    sourceUrl: SRC.openai,
    replacementId: "gpt-6-astra",
    selectable: false,
  },
  {
    id: "gpt-4.1",
    label: "GPT-4.1",
    provider: "openai",
    target: "gpt",
    family: "GPT",
    status: "legacy",
    strengths: ["reasoning", "coding", "long_context"],
    notes: {
      es: "Modelo legacy de la serie GPT-4. Considerá GPT-6 Sol para mejores resultados.",
      en: "Legacy GPT-4-series model. Consider GPT-6 Sol for better results.",
    },
    verifiedAt: VERIFIED,
    sourceUrl: SRC.openai,
    replacementId: "gpt-6-sol",
    selectable: false,
  },
  {
    id: "gpt-4o",
    label: "GPT-4o",
    provider: "openai",
    target: "gpt",
    family: "GPT",
    status: "legacy",
    strengths: ["multimodal", "writing", "speed"],
    notes: {
      es: "Modelo legacy multimodal. Considerá GPT-6 Sol para mejores resultados.",
      en: "Legacy multimodal model. Consider GPT-6 Sol for better results.",
    },
    verifiedAt: VERIFIED,
    sourceUrl: SRC.openai,
    replacementId: "gpt-6-sol",
    selectable: false,
  },
  {
    id: "gpt-4o-mini",
    label: "GPT-4o mini",
    provider: "openai",
    target: "gpt",
    family: "GPT",
    status: "legacy",
    strengths: ["speed", "writing"],
    notes: {
      es: "Modelo legacy liviano. Considerá GPT-6 Luna para mejores resultados.",
      en: "Legacy lightweight model. Consider GPT-6 Luna for better results.",
    },
    verifiedAt: VERIFIED,
    sourceUrl: SRC.openai,
    replacementId: "gpt-6-luna",
    selectable: false,
  },
  {
    id: "gpt-o3",
    label: "OpenAI o3 (reasoning)",
    provider: "openai",
    target: "gpt",
    family: "GPT",
    status: "deprecated",
    strengths: ["reasoning", "coding", "data"],
    notes: {
      es: "Modelo de razonamiento deprecado por OpenAI (se apaga el 2026-12-11). Las capacidades de razonamiento están integradas en GPT-6.",
      en: "Reasoning model deprecated by OpenAI (shutdown 2026-12-11). Reasoning capabilities are integrated into GPT-6.",
    },
    verifiedAt: VERIFIED,
    sourceUrl: "https://developers.openai.com/api/docs/deprecations",
    replacementId: "gpt-6-sol",
    selectable: false,
  },

  // ── Anthropic ─────────────────────────────────────────────────────────────
  {
    id: "claude-opus-5.5",
    label: "Claude Opus 5.5",
    provider: "anthropic",
    target: "claude",
    family: "Claude",
    status: "stable",
    strengths: ["reasoning", "coding", "writing", "long_context", "multimodal"],
    notes: {
      es: "El modelo con el que Anthropic recomienda empezar (GA 22-09-2026): coding agéntico de largo aliento y trabajo de conocimiento, contexto de 1M. Piensa siempre: la profundidad se regula con effort (default medium), no con 'pensá con cuidado' en el prompt.",
      en: "Anthropic's recommended starting model (GA 2026-09-22): long-running agentic coding and knowledge work, 1M context. It always thinks — depth is set with effort (default medium), not with 'think carefully' in the prompt.",
    },
    apiModelId: "claude-opus-5-5",
    verifiedAt: VERIFIED,
    sourceUrl: "https://platform.claude.com/docs/en/models/opus-5-5/overview",
    selectable: true,
    defaultForTarget: true,
    capabilities: {
      inputModalities: ["text", "image", "pdf"],
      outputModalities: ["text"],
      contextWindowTokens: 1000000,
      maxOutputTokens: 128000,
      latencyClass: "balanced",
      structuredOutput: true,
      toolUse: true,
      nativeSearch: true,
      reasoningTier: 3,
      codingAgentFit: 3,
      taskFit: {
        chat: 3,
        coding: 3,
        codingAgent: 3,
        research: 3,
        longContext: 3,
        multimodal: 3,
        dataExtraction: 3,
        creativeWriting: 3,
        marketing: 2,
        translation: 2,
        summarization: 3,
        tutoring: 3,
        imagePrompts: 2,
        complexReasoning: 3,
        fastLightweight: 1,
      },
      promptGuidance: {
        es: "Dale en un solo pedido completo el objetivo, el contexto, las restricciones y cómo se ve 'terminado'; sacá las líneas de 'pensá con cuidado' o 'revisá dos veces': piensa siempre y el effort (default medium) es el control. En frontend nombrá los estilos concretos a evitar, y envolvé el texto pegado de terceros en etiquetas para que sus instrucciones se traten como datos.",
        en: "Give the goal, context, constraints, and what 'done' looks like in one complete request; drop 'think carefully' or 'double-check' lines — it always thinks and effort (default medium) is the control. For frontend work name the specific styles to avoid, and wrap pasted third-party text in tags so its instructions are treated as data.",
      },
    },
    interactionProfiles: ["chat", "codingAgent"],
    promptProfile: "opus-adaptive",
  },
  {
    id: "claude-fable-5.1",
    label: "Claude Fable 5.1",
    provider: "anthropic",
    target: "claude",
    family: "Claude",
    status: "stable",
    strengths: ["reasoning", "writing", "long_context", "coding", "multimodal"],
    notes: {
      es: "El modelo más capaz de Anthropic de acceso general (GA 01-09-2026), para el razonamiento más exigente y corridas autónomas largas. Explicale la intención y marcá límites: las listas de pasos sobre-prescriptivas le bajan la calidad.",
      en: "Anthropic's most capable widely released model (GA 2026-09-01), for the most demanding reasoning and long autonomous runs. Explain the intent and state boundaries — over-prescriptive step lists reduce its quality.",
    },
    apiModelId: "claude-fable-5-1",
    verifiedAt: VERIFIED,
    sourceUrl: "https://platform.claude.com/docs/en/models/fable-5-1/overview",
    selectable: true,
    capabilities: {
      inputModalities: ["text", "image", "pdf"],
      outputModalities: ["text"],
      contextWindowTokens: 1000000,
      maxOutputTokens: 128000,
      latencyClass: "slow",
      structuredOutput: true,
      toolUse: true,
      nativeSearch: true,
      reasoningTier: 3,
      codingAgentFit: 3,
      taskFit: {
        chat: 1,
        coding: 3,
        codingAgent: 3,
        research: 3,
        longContext: 3,
        multimodal: 3,
        dataExtraction: 3,
        creativeWriting: 3,
        marketing: 1,
        translation: 1,
        summarization: 2,
        tutoring: 2,
        imagePrompts: 1,
        complexReasoning: 3,
        fastLightweight: 0,
      },
      promptGuidance: {
        es: "Explicá para quién es y qué habilita el resultado, y expresá objetivos y restricciones en vez de pasos. Marcá qué no tocar, pedí un cierre que empiece por el resultado y mantené tus instrucciones de verificación. El effort arranca en high; bajalo a medium/low donde tus evals lo permitan.",
        en: "Say who the result is for and what it enables, and state goals and constraints instead of steps. Mark what not to touch, ask for a final message that leads with the outcome, and keep your verification instructions. Effort starts at high; step down to medium/low where your evals hold.",
      },
    },
    interactionProfiles: ["chat", "codingAgent"],
    promptProfile: "fable-autonomous",
  },
  {
    id: "claude-sonnet-5",
    label: "Claude Sonnet 5",
    provider: "anthropic",
    target: "claude",
    family: "Claude",
    status: "stable",
    strengths: ["writing", "reasoning", "speed", "long_context"],
    notes: {
      es: "El Claude rápido para coding, agentes y trabajo empresarial del día a día. Usá secciones claras y delimitadores para inputs largos.",
      en: "The fast Claude for everyday coding, agent, and enterprise workloads. Use clear sections and delimiters for long inputs.",
    },
    apiModelId: "claude-sonnet-5",
    openRouterId: "anthropic/claude-sonnet-5",
    verifiedAt: VERIFIED,
    sourceUrl: "https://platform.claude.com/docs/en/models/sonnet-5/overview",
    selectable: true,
    capabilities: {
      inputModalities: ["text", "image", "pdf"],
      outputModalities: ["text"],
      contextWindowTokens: 1000000,
      maxOutputTokens: 128000,
      latencyClass: "fast",
      structuredOutput: true,
      toolUse: true,
      nativeSearch: true,
      reasoningTier: 2,
      codingAgentFit: 3,
      taskFit: {
        chat: 3,
        coding: 3,
        codingAgent: 3,
        research: 2,
        longContext: 3,
        multimodal: 2,
        dataExtraction: 3,
        creativeWriting: 3,
        marketing: 2,
        translation: 2,
        summarization: 3,
        tutoring: 3,
        imagePrompts: 2,
        complexReasoning: 2,
        fastLightweight: 2,
      },
      promptGuidance: {
        es: "Estructurá el prompt con etiquetas XML, poné los documentos largos arriba y la consulta al final, y definí criterios de éxito explícitos. Sigue las instrucciones de forma literal: aclarale el alcance ('aplicalo a todas las secciones') en vez de esperar que generalice.",
        en: "Structure prompts with XML tags, put long documents at the top and the query at the end, and give explicit success criteria. It follows instructions literally — state scope ('apply to every section') rather than expecting generalization.",
      },
    },
    interactionProfiles: ["chat", "codingAgent"],
    promptProfile: "claude-literal",
  },
  {
    id: "claude-haiku-4.5",
    label: "Claude Haiku 4.5",
    provider: "anthropic",
    target: "claude",
    family: "Claude",
    status: "stable",
    strengths: ["speed", "writing"],
    notes: {
      es: "El Claude de menor latencia y precio. Mantené el prompt corto, con tareas claras y formato exacto. Anthropic indica un retiro no antes del 15-10-2026.",
      en: "The lowest-latency, lowest-price Claude. Keep prompts short with clear tasks and an exact output format. Anthropic lists retirement no sooner than 2026-10-15.",
    },
    apiModelId: "claude-haiku-4-5",
    verifiedAt: VERIFIED,
    sourceUrl: "https://platform.claude.com/docs/en/models/haiku-4-5/overview",
    selectable: true,
    capabilities: {
      inputModalities: ["text", "image", "pdf"],
      outputModalities: ["text"],
      contextWindowTokens: 200000,
      maxOutputTokens: 64000,
      latencyClass: "fast",
      structuredOutput: true,
      toolUse: true,
      nativeSearch: true,
      reasoningTier: 1,
      codingAgentFit: 2,
      taskFit: {
        chat: 2,
        coding: 2,
        codingAgent: 2,
        research: 1,
        longContext: 1,
        multimodal: 2,
        dataExtraction: 2,
        creativeWriting: 2,
        marketing: 2,
        translation: 2,
        summarization: 3,
        tutoring: 1,
        imagePrompts: 2,
        complexReasoning: 1,
        fastLightweight: 3,
      },
      promptGuidance: {
        es: "Mantené el prompt corto y explícito: tarea clara, formato de salida exacto y 1-2 ejemplos rinden más que instrucciones largas. Activá el extended thinking (budget_tokens) solo para tareas más difíciles.",
        en: "Keep prompts short and explicit: a clear task, an exact output format, and 1-2 examples outperform long instructions. Enable extended thinking (budget_tokens) only for harder tasks.",
      },
    },
    interactionProfiles: ["chat", "codingAgent"],
    promptProfile: "claude-compact",
  },
  {
    id: "claude-fable-5",
    label: "Claude Fable 5",
    provider: "anthropic",
    target: "claude",
    family: "Claude",
    status: "legacy",
    strengths: ["reasoning", "writing", "long_context", "coding"],
    notes: {
      es: "Generación anterior de Fable (activa como legacy; retiro no antes del 09-06-2027). Usá Claude Fable 5.1.",
      en: "Previous Fable generation (active legacy; retirement no sooner than 2027-06-09). Use Claude Fable 5.1.",
    },
    apiModelId: "claude-fable-5",
    openRouterId: "anthropic/claude-fable-5",
    verifiedAt: VERIFIED,
    sourceUrl: "https://platform.claude.com/docs/en/models/fable-5/overview",
    replacementId: "claude-fable-5.1",
    selectable: false,
  },
  {
    id: "claude-opus-5",
    label: "Claude Opus 5",
    provider: "anthropic",
    target: "claude",
    family: "Claude",
    status: "legacy",
    strengths: ["reasoning", "coding", "long_context"],
    notes: {
      es: "Opus anterior (activo como legacy; retiro no antes del 24-07-2027). Usá Claude Opus 5.5: más rápido, más barato y con effort medium por defecto.",
      en: "Previous Opus (active legacy; retirement no sooner than 2027-07-24). Use Claude Opus 5.5 — faster, cheaper, and medium effort by default.",
    },
    apiModelId: "claude-opus-5",
    verifiedAt: VERIFIED,
    sourceUrl: "https://platform.claude.com/docs/en/models/opus-5/overview",
    replacementId: "claude-opus-5.5",
    selectable: false,
  },
  {
    id: "claude-opus-4.8",
    label: "Claude Opus 4.8",
    provider: "anthropic",
    target: "claude",
    family: "Claude",
    status: "legacy",
    strengths: ["reasoning", "coding", "long_context"],
    notes: {
      es: "Generación anterior de Opus (legacy; retiro no antes del 28-05-2027). Usá Claude Opus 5.5.",
      en: "Previous Opus generation (legacy; retirement no sooner than 2027-05-28). Use Claude Opus 5.5.",
    },
    apiModelId: "claude-opus-4-8",
    openRouterId: "anthropic/claude-opus-4.8",
    verifiedAt: VERIFIED,
    sourceUrl: "https://platform.claude.com/docs/en/about-claude/model-deprecations",
    replacementId: "claude-opus-5.5",
    selectable: false,
  },
  {
    id: "claude-sonnet",
    label: "Claude Sonnet (legacy alias)",
    provider: "anthropic",
    target: "claude",
    family: "Claude",
    status: "legacy",
    strengths: ["writing", "reasoning", "long_context"],
    notes: {
      es: "Alias genérico legacy. Usá Claude Sonnet 5.",
      en: "Legacy generic alias. Use Claude Sonnet 5.",
    },
    verifiedAt: VERIFIED,
    sourceUrl: SRC.anthropic,
    replacementId: "claude-sonnet-5",
    selectable: false,
  },
  {
    id: "claude-opus",
    label: "Claude Opus (legacy alias)",
    provider: "anthropic",
    target: "claude",
    family: "Claude",
    status: "legacy",
    strengths: ["reasoning", "writing", "long_context"],
    notes: {
      es: "Alias genérico legacy. Usá Claude Opus 5.5.",
      en: "Legacy generic alias. Use Claude Opus 5.5.",
    },
    verifiedAt: VERIFIED,
    sourceUrl: SRC.anthropic,
    replacementId: "claude-opus-5.5",
    selectable: false,
  },
  {
    id: "claude-haiku",
    label: "Claude Haiku (legacy alias)",
    provider: "anthropic",
    target: "claude",
    family: "Claude",
    status: "legacy",
    strengths: ["speed", "writing"],
    notes: {
      es: "Alias genérico legacy. Usá Claude Haiku 4.5.",
      en: "Legacy generic alias. Use Claude Haiku 4.5.",
    },
    verifiedAt: VERIFIED,
    sourceUrl: SRC.anthropic,
    replacementId: "claude-haiku-4.5",
    selectable: false,
  },

  // ── Google ────────────────────────────────────────────────────────────────
  {
    id: "gemini-3.8-flash",
    label: "Gemini 3.8 Flash",
    provider: "google",
    target: "gemini",
    family: "Gemini",
    status: "stable",
    strengths: ["coding", "reasoning", "speed", "multimodal", "long_context"],
    notes: {
      es: "El Flash más inteligente de Google (GA sep 2026), para ingeniería de software de largo aliento, agentes autónomos y flujos empresariales complejos. Tiende a respuestas cortas: pedile detalle si lo necesitás.",
      en: "Google's most intelligent Flash (GA Sep 2026), for long-horizon software engineering, autonomous agents, and complex enterprise workflows. Defaults to terse answers; ask for detail when you need it.",
    },
    apiModelId: "gemini-3.8-flash",
    verifiedAt: VERIFIED,
    sourceUrl: SRC.google,
    selectable: true,
    defaultForTarget: true,
    capabilities: {
      inputModalities: ["text", "image", "audio", "video", "pdf"],
      outputModalities: ["text"],
      contextWindowTokens: 1048576,
      maxOutputTokens: 65536,
      latencyClass: "fast",
      structuredOutput: true,
      toolUse: true,
      nativeSearch: true,
      reasoningTier: 3,
      codingAgentFit: 3,
      taskFit: {
        chat: 3,
        coding: 3,
        codingAgent: 3,
        research: 3,
        longContext: 3,
        multimodal: 3,
        dataExtraction: 3,
        creativeWriting: 2,
        marketing: 2,
        translation: 2,
        summarization: 3,
        tutoring: 2,
        imagePrompts: 2,
        complexReasoning: 3,
        fastLightweight: 2,
      },
      promptGuidance: {
        es: "Con inputs largos, contexto primero e instrucción al final, con un solo estilo de delimitadores. thinking_level arranca en medium (low, medium o high; minimal no está disponible) y los parámetros de sampling están deprecados: no los envíes. Por defecto es escueto, así que pedí detalle de forma explícita.",
        en: "For long inputs put context first and the instruction last, with one consistent delimiter style. thinking_level defaults to medium (low, medium, or high; minimal is unavailable) and sampling parameters are deprecated — don't send them. It is terse by default, so ask for detail explicitly.",
      },
    },
    interactionProfiles: ["chat", "multimodalAssistant", "codingAgent"],
    promptProfile: "gemini-context-first",
  },
  {
    id: "gemini-3.7-flash",
    label: "Gemini 3.7 Flash",
    provider: "google",
    target: "gemini",
    family: "Gemini",
    status: "stable",
    strengths: ["coding", "speed", "multimodal", "long_context"],
    notes: {
      es: "Flash de la generación anterior (GA ago 2026) para coding complejo y flujos agénticos. Mismo contexto de 1M y multimodal completo.",
      en: "Previous-generation Flash (GA Aug 2026) for complex coding and agentic workflows. Same 1M context and full multimodality.",
    },
    apiModelId: "gemini-3.7-flash",
    verifiedAt: VERIFIED,
    sourceUrl: SRC.google,
    selectable: true,
    capabilities: {
      inputModalities: ["text", "image", "audio", "video", "pdf"],
      outputModalities: ["text"],
      contextWindowTokens: 1048576,
      maxOutputTokens: 65536,
      latencyClass: "fast",
      structuredOutput: true,
      toolUse: true,
      nativeSearch: true,
      reasoningTier: 2,
      codingAgentFit: 3,
      taskFit: {
        chat: 3,
        coding: 3,
        codingAgent: 3,
        research: 2,
        longContext: 3,
        multimodal: 3,
        dataExtraction: 3,
        creativeWriting: 2,
        marketing: 2,
        translation: 2,
        summarization: 3,
        tutoring: 2,
        imagePrompts: 2,
        complexReasoning: 2,
        fastLightweight: 2,
      },
      promptGuidance: {
        es: "Contexto primero e instrucciones al final para inputs largos, con delimitadores consistentes. thinking_level por defecto medium (low, medium o high); pedí prosa detallada de forma explícita porque por defecto es escueto.",
        en: "Context first and instructions last for long inputs, with consistent delimiters. thinking_level defaults to medium (low, medium, or high); ask explicitly for detailed prose because it is terse by default.",
      },
    },
    interactionProfiles: ["chat", "multimodalAssistant", "codingAgent"],
    promptProfile: "gemini-context-first",
  },
  {
    id: "gemini-3.6-flash",
    label: "Gemini 3.6 Flash",
    provider: "google",
    target: "gemini",
    family: "Gemini",
    status: "stable",
    strengths: ["speed", "multimodal", "long_context", "coding"],
    notes: {
      es: "Flash GA (jul 2026) que balancea velocidad y multimodalidad para tareas agénticas generales. Tiende a respuestas cortas; pedile detalle si lo necesitás.",
      en: "GA Flash (Jul 2026) balancing speed and multimodality for general agentic tasks. Defaults to terse answers; ask for detail when you need it.",
    },
    apiModelId: "gemini-3.6-flash",
    verifiedAt: VERIFIED,
    sourceUrl: SRC.google,
    selectable: true,
    capabilities: {
      inputModalities: ["text", "image", "audio", "video", "pdf"],
      outputModalities: ["text"],
      contextWindowTokens: 1048576,
      maxOutputTokens: 65536,
      latencyClass: "fast",
      structuredOutput: true,
      toolUse: true,
      nativeSearch: true,
      reasoningTier: 2,
      codingAgentFit: 3,
      taskFit: {
        chat: 3,
        coding: 3,
        codingAgent: 3,
        research: 2,
        longContext: 3,
        multimodal: 3,
        dataExtraction: 3,
        creativeWriting: 2,
        marketing: 2,
        translation: 2,
        summarization: 3,
        tutoring: 2,
        imagePrompts: 2,
        complexReasoning: 2,
        fastLightweight: 2,
      },
      promptGuidance: {
        es: "Para inputs largos poné el contexto primero y las instrucciones al final, con un solo estilo de delimitadores. Controlá la profundidad con thinking_level (default medium; admite minimal); por defecto es escueto, así que pedile prosa detallada de forma explícita.",
        en: "Place context first and instructions at the end for long inputs, using one consistent delimiter style. Control depth with thinking_level (default medium; minimal is available); it is terse by default, so ask explicitly for detailed prose.",
      },
    },
    interactionProfiles: ["chat", "multimodalAssistant", "codingAgent"],
    promptProfile: "gemini-context-first",
  },
  {
    id: "gemini-3.5-flash-lite",
    label: "Gemini 3.5 Flash-Lite",
    provider: "google",
    target: "gemini",
    family: "Gemini",
    status: "stable",
    strengths: ["speed", "multimodal", "data"],
    notes: {
      es: "El modelo 3.5 más rápido y barato. Google lo recomienda (junto a 3.8 Flash) para proyectos nuevos de alto volumen, como extracción de datos y subagentes.",
      en: "The fastest, lowest-cost 3.5 model. Google recommends it (alongside 3.8 Flash) for new high-volume work such as data extraction and subagents.",
    },
    apiModelId: "gemini-3.5-flash-lite",
    verifiedAt: VERIFIED,
    sourceUrl: SRC.google,
    selectable: true,
    capabilities: {
      inputModalities: ["text", "image", "audio", "video", "pdf"],
      outputModalities: ["text"],
      contextWindowTokens: 1048576,
      maxOutputTokens: 65536,
      latencyClass: "fast",
      structuredOutput: true,
      toolUse: true,
      nativeSearch: true,
      reasoningTier: 1,
      codingAgentFit: 1,
      taskFit: {
        chat: 2,
        coding: 1,
        codingAgent: 1,
        research: 1,
        longContext: 2,
        multimodal: 2,
        dataExtraction: 3,
        creativeWriting: 1,
        marketing: 1,
        translation: 2,
        summarization: 2,
        tutoring: 1,
        imagePrompts: 1,
        complexReasoning: 1,
        fastLightweight: 3,
      },
      promptGuidance: {
        es: "Mantené el prompt compacto, con instrucciones explícitas y un formato o schema de salida exacto; subí thinking_level desde el mínimo por defecto cuando la tarea necesite lógica de varios pasos, y sumá un ejemplo corto del resultado esperado.",
        en: "Keep prompts compact with explicit instructions and an exact output format or schema; raise thinking_level from the minimal default when a task needs multi-step logic, and add one short example of the expected result.",
      },
    },
    interactionProfiles: ["chat", "multimodalAssistant"],
    promptProfile: "gemini-context-first",
  },
  {
    id: "gemini-3.1-pro",
    label: "Gemini 3.1 Pro",
    provider: "google",
    target: "gemini",
    family: "Gemini",
    status: "preview",
    strengths: ["reasoning", "multimodal", "long_context", "data"],
    notes: {
      es: "Inteligencia avanzada para problemas complejos (sigue en preview; no hay un Pro más nuevo). Pedí que marque supuestos y dé formato visible.",
      en: "Advanced intelligence for complex problem-solving (still in preview; there is no newer Pro). Ask it to state assumptions and use a visible format.",
    },
    apiModelId: "gemini-3.1-pro-preview",
    verifiedAt: VERIFIED,
    sourceUrl: SRC.google,
    selectable: true,
    capabilities: {
      inputModalities: ["text", "image", "audio", "video", "pdf"],
      outputModalities: ["text"],
      contextWindowTokens: 1048576,
      maxOutputTokens: 65536,
      latencyClass: "slow",
      structuredOutput: true,
      toolUse: true,
      nativeSearch: true,
      reasoningTier: 3,
      codingAgentFit: 2,
      taskFit: {
        chat: 2,
        coding: 3,
        codingAgent: 2,
        research: 3,
        longContext: 3,
        multimodal: 3,
        dataExtraction: 2,
        creativeWriting: 2,
        marketing: 2,
        translation: 2,
        summarization: 2,
        tutoring: 3,
        imagePrompts: 2,
        complexReasoning: 3,
        fastLightweight: 0,
      },
      promptGuidance: {
        es: "Pedile que marque supuestos en problemas complejos; thinking_level arranca en high (low, medium o high). Contexto primero e instrucciones al final para inputs largos, con delimitadores consistentes.",
        en: "Ask it to state assumptions on complex problems; thinking_level defaults to high (low, medium, or high). Context first, instructions last for long inputs, with consistent delimiters.",
      },
    },
    interactionProfiles: ["chat", "multimodalAssistant"],
    promptProfile: "gemini-context-first",
  },
  {
    id: "gemini-3.5-flash",
    label: "Gemini 3.5 Flash",
    provider: "google",
    target: "gemini",
    family: "Gemini",
    status: "legacy",
    strengths: ["speed", "multimodal", "long_context", "coding"],
    notes: {
      es: "Google ahora lo marca como 'Legacy Flash' (sigue disponible y cuesta más que 3.6-3.8). Usá Gemini 3.8 Flash.",
      en: "Google now labels it a 'Legacy Flash model' (still served, and priced above 3.6–3.8). Use Gemini 3.8 Flash.",
    },
    apiModelId: "gemini-3.5-flash",
    openRouterId: "google/gemini-3.5-flash",
    verifiedAt: VERIFIED,
    sourceUrl: SRC.google,
    replacementId: "gemini-3.8-flash",
    selectable: false,
  },
  {
    id: "gemini-3.1-flash-lite",
    label: "Gemini 3.1 Flash-Lite",
    provider: "google",
    target: "gemini",
    family: "Gemini",
    status: "deprecated",
    strengths: ["speed", "multimodal"],
    notes: {
      es: "Deprecado por Google: se apaga el 07-05-2027 y lo reemplaza Gemini 3.5 Flash-Lite.",
      en: "Deprecated by Google: shuts down 2027-05-07, replaced by Gemini 3.5 Flash-Lite.",
    },
    apiModelId: "gemini-3.1-flash-lite",
    verifiedAt: VERIFIED,
    sourceUrl: "https://ai.google.dev/gemini-api/docs/deprecations",
    replacementId: "gemini-3.5-flash-lite",
    selectable: false,
  },
  {
    id: "gemini-pro",
    label: "Gemini Pro (legacy alias)",
    provider: "google",
    target: "gemini",
    family: "Gemini",
    status: "legacy",
    strengths: ["multimodal", "long_context", "data"],
    notes: {
      es: "Alias genérico legacy. Usá Gemini 3.1 Pro o Gemini 3.8 Flash.",
      en: "Legacy generic alias. Use Gemini 3.1 Pro or Gemini 3.8 Flash.",
    },
    verifiedAt: VERIFIED,
    sourceUrl: SRC.google,
    replacementId: "gemini-3.1-pro",
    selectable: false,
  },
  {
    id: "gemini-flash",
    label: "Gemini Flash (legacy alias)",
    provider: "google",
    target: "gemini",
    family: "Gemini",
    status: "legacy",
    strengths: ["speed", "multimodal"],
    notes: {
      es: "Alias genérico legacy. Usá Gemini 3.8 Flash.",
      en: "Legacy generic alias. Use Gemini 3.8 Flash.",
    },
    verifiedAt: VERIFIED,
    sourceUrl: SRC.google,
    replacementId: "gemini-3.8-flash",
    selectable: false,
  },

  // ── xAI ───────────────────────────────────────────────────────────────────
  {
    id: "grok-4.7",
    label: "Grok 4.7",
    provider: "xai",
    target: "grok",
    family: "Grok",
    status: "stable",
    strengths: ["reasoning", "coding", "writing", "search"],
    notes: {
      es: "El Grok más capaz (sep 2026) y el que xAI recomienda para código y chat (contexto 500k). Tono directo; definí tono y nivel de informalidad.",
      en: "The most capable Grok (Sep 2026) and xAI's recommendation for code and chat (500k context). Direct tone; define tone and informality for best results.",
    },
    apiModelId: "grok-4.7",
    verifiedAt: VERIFIED,
    sourceUrl: "https://docs.x.ai/developers/grok-4-7",
    selectable: true,
    defaultForTarget: true,
    capabilities: {
      inputModalities: ["text", "image"],
      outputModalities: ["text"],
      contextWindowTokens: 500000,
      maxOutputTokens: null,
      latencyClass: "balanced",
      structuredOutput: true,
      toolUse: true,
      nativeSearch: true,
      reasoningTier: 3,
      codingAgentFit: 3,
      taskFit: {
        chat: 3,
        coding: 3,
        codingAgent: 2,
        research: 3,
        longContext: 2,
        multimodal: 1,
        dataExtraction: 2,
        creativeWriting: 2,
        marketing: 2,
        translation: 2,
        summarization: 2,
        tutoring: 2,
        imagePrompts: 2,
        complexReasoning: 3,
        fastLightweight: 1,
      },
      promptGuidance: {
        es: "El razonamiento no se puede apagar: reasoning_effort va de low a xhigh (default high), bajalo para agentes sensibles a la latencia. Poné primero el contenido estable y la pregunta al final, activá la búsqueda web/X para temas actuales y especificá el tono: por defecto es directo.",
        en: "Reasoning can't be turned off: reasoning_effort runs low to xhigh (default high) — lower it for latency-sensitive agents. Put stable content first and the question last, enable web/X search for current events, and specify tone — it is direct by default.",
      },
    },
    interactionProfiles: ["chat", "researchAssistant"],
    promptProfile: "grok-general",
  },
  {
    id: "grok-4.3",
    label: "Grok 4.3",
    provider: "xai",
    target: "grok",
    family: "Grok",
    status: "stable",
    strengths: ["reasoning", "writing", "long_context"],
    notes: {
      es: "Grok con contexto de 1M tokens y precio más bajo. Útil para material largo; separá fuente e instrucciones.",
      en: "Grok with a 1M-token context at a lower price. Useful for long material; separate source text from instructions.",
    },
    apiModelId: "grok-4.3",
    openRouterId: "x-ai/grok-4.3",
    verifiedAt: VERIFIED,
    sourceUrl: "https://docs.x.ai/developers/models/grok-4.3",
    selectable: true,
    capabilities: {
      inputModalities: ["text", "image", "pdf"],
      outputModalities: ["text"],
      contextWindowTokens: 1000000,
      maxOutputTokens: null,
      latencyClass: "fast",
      structuredOutput: true,
      toolUse: true,
      nativeSearch: true,
      reasoningTier: 2,
      codingAgentFit: 2,
      taskFit: {
        chat: 3,
        coding: 2,
        codingAgent: 2,
        research: 2,
        longContext: 3,
        multimodal: 1,
        dataExtraction: 2,
        creativeWriting: 2,
        marketing: 2,
        translation: 2,
        summarization: 3,
        tutoring: 2,
        imagePrompts: 1,
        complexReasoning: 2,
        fastLightweight: 2,
      },
      promptGuidance: {
        es: "reasoning_effort admite 'none' (default low): usalo para respuestas rápidas y subilo cuando haga falta razonar. Con documentos largos, separá el material fuente de las instrucciones con etiquetas XML o títulos, y mantené un prefijo estable para aprovechar el caching.",
        en: "reasoning_effort supports 'none' (default low): use it for fast replies and raise it when reasoning is needed. For long documents, separate source material from instructions with XML tags or headings, and keep a stable prefix to exploit caching.",
      },
    },
    interactionProfiles: ["chat"],
    promptProfile: "grok-general",
  },
  {
    id: "grok-build-0.1",
    label: "Grok Build 0.1",
    provider: "xai",
    target: "grok",
    family: "Grok",
    status: "stable",
    strengths: ["coding", "reasoning"],
    notes: {
      es: "Grok especializado en coding agéntico (motor del Grok Build CLI; también atiende el alias grok-code-fast-1). Pedí criterios de corrección y casos borde.",
      en: "Agentic-coding-specialized Grok (powers the Grok Build CLI; also serves the grok-code-fast-1 alias). Ask for correctness criteria and edge cases.",
    },
    apiModelId: "grok-build-0.1",
    openRouterId: "x-ai/grok-build-0.1",
    verifiedAt: VERIFIED,
    sourceUrl: "https://docs.x.ai/developers/models/grok-build-0.1",
    selectable: true,
    capabilities: {
      inputModalities: ["text", "image"],
      outputModalities: ["text"],
      contextWindowTokens: 256000,
      maxOutputTokens: null,
      latencyClass: "fast",
      structuredOutput: true,
      toolUse: true,
      nativeSearch: false,
      reasoningTier: 2,
      codingAgentFit: 3,
      taskFit: {
        chat: 1,
        coding: 3,
        codingAgent: 3,
        research: 1,
        longContext: 2,
        multimodal: 1,
        dataExtraction: 2,
        creativeWriting: 0,
        marketing: 0,
        translation: 1,
        summarization: 1,
        tutoring: 1,
        imagePrompts: 0,
        complexReasoning: 2,
        fastLightweight: 1,
      },
      promptGuidance: {
        es: "Señalale los archivos y secciones relevantes en vez de tirarle todo el repo: el contexto irrelevante lo degrada. Estructurá objetivos, restricciones y contexto con títulos o etiquetas XML, definí criterios de corrección explícitos e iterá en diffs chicos.",
        en: "Point it at the specific files and sections relevant to the task instead of dumping the whole repo — irrelevant context degrades it. Structure goals, constraints, and context with headings or XML tags, state explicit correctness criteria, and iterate in small diffs.",
      },
    },
    interactionProfiles: ["codingAgent", "codeSpecialist"],
    promptProfile: "grok-code",
  },
  {
    id: "grok-4.5",
    label: "Grok 4.5",
    provider: "xai",
    target: "grok",
    family: "Grok",
    status: "legacy",
    strengths: ["reasoning", "writing", "speed", "search"],
    notes: {
      es: "Generación anterior (sigue disponible, mismo precio que 4.7). Usá Grok 4.7.",
      en: "Previous generation (still served, same price as 4.7). Use Grok 4.7.",
    },
    apiModelId: "grok-4.5",
    verifiedAt: VERIFIED,
    sourceUrl: SRC.xai,
    replacementId: "grok-4.7",
    selectable: false,
  },
  {
    id: "grok-2",
    label: "Grok (legacy)",
    provider: "xai",
    target: "grok",
    family: "Grok",
    status: "deprecated",
    strengths: ["writing", "speed"],
    notes: {
      es: "Familia Grok 2 retirada por xAI. Usá Grok 4.7.",
      en: "Grok 2 family retired by xAI. Use Grok 4.7.",
    },
    verifiedAt: VERIFIED,
    sourceUrl: SRC.xai,
    replacementId: "grok-4.7",
    selectable: false,
  },

  // ── DeepSeek ──────────────────────────────────────────────────────────────
  {
    id: "deepseek-flash",
    label: "DeepSeek Flash (V4.1)",
    provider: "deepseek",
    target: "deepseek",
    family: "DeepSeek",
    status: "stable",
    strengths: ["coding", "speed", "reasoning", "multimodal"],
    notes: {
      es: "Modelo estándar de DeepSeek (V4.1-Flash, sep 2026): contexto 1M, entrada de texto e imagen, modos thinking y non-thinking. Pedí tests y edge cases para código.",
      en: "DeepSeek's standard model (V4.1-Flash, Sep 2026): 1M context, text and image input, thinking and non-thinking modes. Ask for tests and edge cases for code.",
    },
    apiModelId: "deepseek-flash",
    verifiedAt: VERIFIED,
    sourceUrl: SRC.deepseek,
    selectable: true,
    defaultForTarget: true,
    capabilities: {
      inputModalities: ["text", "image"],
      outputModalities: ["text"],
      contextWindowTokens: 1000000,
      maxOutputTokens: 384000,
      latencyClass: "fast",
      structuredOutput: true,
      toolUse: true,
      nativeSearch: false,
      reasoningTier: 2,
      codingAgentFit: 2,
      taskFit: {
        chat: 2,
        coding: 2,
        codingAgent: 2,
        research: 1,
        longContext: 3,
        multimodal: 1,
        dataExtraction: 2,
        creativeWriting: 1,
        marketing: 1,
        translation: 2,
        summarization: 2,
        tutoring: 2,
        imagePrompts: 1,
        complexReasoning: 2,
        fastLightweight: 3,
      },
      promptGuidance: {
        es: "El modo thinking viene activado (effort high por defecto): bajalo a low o 'none' para tareas rápidas. En modo JSON incluí la palabra 'json' y un ejemplo del formato con max_tokens generoso, y devolvé el reasoning_content completo en loops con herramientas.",
        en: "Thinking is on by default (effort high): drop to low or 'none' for quick tasks. In JSON mode include the word 'json' plus an example of the format with generous max_tokens, and pass reasoning_content back in full in tool loops.",
      },
    },
    interactionProfiles: ["chat", "codeSpecialist"],
    promptProfile: "deepseek-reasoner",
  },
  {
    id: "deepseek-v4-pro",
    label: "DeepSeek V4 Pro",
    provider: "deepseek",
    target: "deepseek",
    family: "DeepSeek",
    status: "stable",
    strengths: ["coding", "reasoning", "data"],
    notes: {
      es: "El DeepSeek más capaz (V4-Pro-0813, solo texto): excelente para razonamiento y código con criterios de aceptación explícitos.",
      en: "DeepSeek's most capable model (V4-Pro-0813, text only): excels at reasoning and code with explicit acceptance criteria.",
    },
    apiModelId: "deepseek-v4-pro",
    openRouterId: "deepseek/deepseek-v4-pro",
    verifiedAt: VERIFIED,
    sourceUrl: SRC.deepseek,
    selectable: true,
    capabilities: {
      inputModalities: ["text"],
      outputModalities: ["text"],
      contextWindowTokens: 1000000,
      maxOutputTokens: 384000,
      latencyClass: "balanced",
      structuredOutput: true,
      toolUse: true,
      nativeSearch: false,
      reasoningTier: 3,
      codingAgentFit: 3,
      taskFit: {
        chat: 2,
        coding: 3,
        codingAgent: 3,
        research: 1,
        longContext: 3,
        multimodal: 0,
        dataExtraction: 2,
        creativeWriting: 1,
        marketing: 1,
        translation: 2,
        summarization: 2,
        tutoring: 2,
        imagePrompts: 1,
        complexReasoning: 3,
        fastLightweight: 1,
      },
      promptGuidance: {
        es: "Dale criterios de aceptación, tests y casos borde explícitos para código, y elegí el effort por tarea (low simple, high agentes del día a día, max lo complejo). En modo thinking ignora los parámetros de sampling: guialo con instrucciones, no con temperature.",
        en: "Give explicit acceptance criteria, tests, and edge cases for code, and pick effort per task (low for simple, high for daily agent work, max for complex). Sampling params are ignored in thinking mode — steer with instructions, not temperature.",
      },
    },
    interactionProfiles: ["chat", "codeSpecialist", "codingAgent"],
    promptProfile: "deepseek-reasoner",
  },
  {
    id: "deepseek-v4-flash",
    label: "DeepSeek V4 Flash",
    provider: "deepseek",
    target: "deepseek",
    family: "DeepSeek",
    status: "legacy",
    strengths: ["coding", "speed", "reasoning"],
    notes: {
      es: "Nombre legacy: DeepSeek lo sigue aceptando pero lo atiende V4.1-Flash. Usá deepseek-flash.",
      en: "Legacy name: DeepSeek still accepts it but serves it with V4.1-Flash. Use deepseek-flash.",
    },
    apiModelId: "deepseek-v4-flash",
    openRouterId: "deepseek/deepseek-v4-flash",
    verifiedAt: VERIFIED,
    sourceUrl: SRC.deepseek,
    replacementId: "deepseek-flash",
    selectable: false,
  },
  {
    id: "deepseek-chat",
    label: "DeepSeek Chat (deprecated)",
    provider: "deepseek",
    target: "deepseek",
    family: "DeepSeek",
    status: "deprecated",
    strengths: ["coding", "reasoning"],
    notes: {
      es: "Alias retirado por DeepSeek el 2026-07-24 (ya no resuelve). Usá DeepSeek Flash.",
      en: "Alias retired by DeepSeek on 2026-07-24 (no longer resolves). Use DeepSeek Flash.",
    },
    verifiedAt: VERIFIED,
    sourceUrl: "https://api-docs.deepseek.com/updates",
    replacementId: "deepseek-flash",
    selectable: false,
  },

  // ── Perplexity (Agent API presets) ────────────────────────────────────────
  // Sonar Chat Completions is supported only until 2026-09-27; Perplexity's
  // replacement is the Agent API, where a PRESET (fast/low/medium/high) is the
  // unit you choose. apiModelId holds the preset name.
  {
    id: "perplexity-agent-low",
    label: "Perplexity Agent · low",
    provider: "perplexity",
    target: "perplexity",
    family: "Perplexity Agent API",
    status: "stable",
    strengths: ["search", "writing"],
    notes: {
      es: "Preset de la Agent API para preguntas de investigación del día a día (búsqueda web + lectura de URLs, hasta 5 pasos). Perplexity lo recomienda como punto de partida; reemplaza a Sonar Pro.",
      en: "Agent API preset for everyday research questions (web search + URL fetch, up to 5 steps). Perplexity's recommended starting point; replaces Sonar Pro.",
    },
    apiModelId: "low",
    verifiedAt: VERIFIED,
    sourceUrl: SRC.perplexity,
    selectable: true,
    defaultForTarget: true,
    capabilities: {
      inputModalities: ["text"],
      outputModalities: ["text"],
      contextWindowTokens: null,
      maxOutputTokens: null,
      latencyClass: "balanced",
      structuredOutput: false,
      toolUse: false,
      nativeSearch: true,
      reasoningTier: 1,
      codingAgentFit: 0,
      taskFit: {
        chat: 2,
        coding: 1,
        codingAgent: 0,
        research: 3,
        longContext: 1,
        multimodal: 0,
        dataExtraction: 1,
        creativeWriting: 0,
        marketing: 1,
        translation: 0,
        summarization: 2,
        tutoring: 1,
        imagePrompts: 0,
        complexReasoning: 1,
        fastLightweight: 1,
      },
      promptGuidance: {
        es: "La pregunta es la semilla de la búsqueda: hacela específica, con el vocabulario de las páginas que querés encontrar. Instrucciones cortas (se releen en cada paso), filtros de dominio/fecha como parámetros y no en prosa, sin respuestas de ejemplo, y leé las fuentes desde search_results, no del texto.",
        en: "The question seeds the search: make it specific, with the vocabulary of the pages you want found. Keep instructions short (they are re-read every step), express domain/date limits as parameters, not prose, skip example answers, and read sources from search_results, not the text.",
      },
    },
    interactionProfiles: ["researchAssistant"],
    promptProfile: "perplexity-search",
  },
  {
    id: "perplexity-agent-fast",
    label: "Perplexity Agent · fast",
    provider: "perplexity",
    target: "perplexity",
    family: "Perplexity Agent API",
    status: "stable",
    strengths: ["search", "speed"],
    notes: {
      es: "Preset de la Agent API para búsquedas de un dato, definiciones y resúmenes rápidos (un paso, sin razonamiento). Reemplaza a Sonar.",
      en: "Agent API preset for single-fact lookups, definitions, and quick summaries (one step, no reasoning). Replaces Sonar.",
    },
    apiModelId: "fast",
    verifiedAt: VERIFIED,
    sourceUrl: SRC.perplexity,
    selectable: true,
    capabilities: {
      inputModalities: ["text"],
      outputModalities: ["text"],
      contextWindowTokens: null,
      maxOutputTokens: null,
      latencyClass: "fast",
      structuredOutput: false,
      toolUse: false,
      nativeSearch: true,
      reasoningTier: 0,
      codingAgentFit: 0,
      taskFit: {
        chat: 2,
        coding: 0,
        codingAgent: 0,
        research: 2,
        longContext: 1,
        multimodal: 0,
        dataExtraction: 1,
        creativeWriting: 0,
        marketing: 1,
        translation: 0,
        summarization: 2,
        tutoring: 1,
        imagePrompts: 0,
        complexReasoning: 0,
        fastLightweight: 2,
      },
      promptGuidance: {
        es: "Una pregunta puntual y específica, con 2-3 palabras de contexto para desambiguar: una consulta vaga produce búsquedas vagas. Pedí que avise si no encuentra la respuesta.",
        en: "One pointed, specific question with 2-3 disambiguating context words — vague queries produce vague searches. Ask it to say when it can't find the answer.",
      },
    },
    interactionProfiles: ["researchAssistant"],
    promptProfile: "perplexity-search",
  },
  {
    id: "perplexity-agent-medium",
    label: "Perplexity Agent · medium",
    provider: "perplexity",
    target: "perplexity",
    family: "Perplexity Agent API",
    status: "stable",
    strengths: ["search", "reasoning"],
    notes: {
      es: "Preset de la Agent API para navegación de varios saltos y agregación amplia de fuentes (hasta 15 pasos). Reemplaza a Sonar Reasoning Pro.",
      en: "Agent API preset for multi-hop browsing and wide aggregation across many sources (up to 15 steps). Replaces Sonar Reasoning Pro.",
    },
    apiModelId: "medium",
    verifiedAt: VERIFIED,
    sourceUrl: SRC.perplexity,
    selectable: true,
    capabilities: {
      inputModalities: ["text"],
      outputModalities: ["text"],
      contextWindowTokens: null,
      maxOutputTokens: null,
      latencyClass: "balanced",
      structuredOutput: false,
      toolUse: false,
      nativeSearch: true,
      reasoningTier: 2,
      codingAgentFit: 0,
      taskFit: {
        chat: 1,
        coding: 1,
        codingAgent: 0,
        research: 3,
        longContext: 1,
        multimodal: 0,
        dataExtraction: 1,
        creativeWriting: 0,
        marketing: 1,
        translation: 0,
        summarization: 2,
        tutoring: 2,
        imagePrompts: 0,
        complexReasoning: 2,
        fastLightweight: 0,
      },
      promptGuidance: {
        es: "Poné la pregunta analítica completa, con todos los detalles buscables. Limitá la cantidad de ítems si querés una lista y pedí que marque resultados casi coincidentes (otro año, otra empresa).",
        en: "Put the full analytical question with every searchable specific. Cap the item count if you want a list, and ask it to flag near-miss results (a different year, a related company).",
      },
    },
    interactionProfiles: ["researchAssistant"],
    promptProfile: "perplexity-search",
  },
  {
    id: "perplexity-agent-high",
    label: "Perplexity Agent · high",
    provider: "perplexity",
    target: "perplexity",
    family: "Perplexity Agent API",
    status: "stable",
    strengths: ["search", "reasoning", "long_context"],
    notes: {
      es: "Preset de la Agent API para razonamiento experto y cobertura exhaustiva de fuentes. Reemplaza a Sonar Deep Research; definí alcance, período y formato del informe.",
      en: "Agent API preset for expert-level reasoning and exhaustive source coverage. Replaces Sonar Deep Research; define scope, time period, and report format.",
    },
    apiModelId: "high",
    verifiedAt: VERIFIED,
    sourceUrl: SRC.perplexity,
    selectable: true,
    capabilities: {
      inputModalities: ["text"],
      outputModalities: ["text"],
      contextWindowTokens: null,
      maxOutputTokens: null,
      latencyClass: "slow",
      structuredOutput: false,
      toolUse: false,
      nativeSearch: true,
      reasoningTier: 2,
      codingAgentFit: 0,
      taskFit: {
        chat: 0,
        coding: 0,
        codingAgent: 0,
        research: 3,
        longContext: 2,
        multimodal: 0,
        dataExtraction: 1,
        creativeWriting: 0,
        marketing: 1,
        translation: 0,
        summarization: 2,
        tutoring: 1,
        imagePrompts: 0,
        complexReasoning: 2,
        fastLightweight: 0,
      },
      promptGuidance: {
        es: "Tratá el prompt como un brief de investigación, no como una pregunta: definí de entrada alcance, período, geografía, dimensiones de análisis y estructura del informe (máximo 5 secciones).",
        en: "Treat the prompt as a research brief, not a question: define scope, time period, geography, analysis dimensions, and report structure up front (at most 5 sections).",
      },
    },
    interactionProfiles: ["researchAssistant"],
    promptProfile: "perplexity-search",
  },
  {
    id: "sonar-pro",
    label: "Sonar Pro",
    provider: "perplexity",
    target: "perplexity",
    family: "Sonar",
    status: "deprecated",
    strengths: ["search", "writing"],
    notes: {
      es: "Sonar Chat Completions tiene soporte solo hasta el 27-09-2026. Perplexity lo mapea al preset 'low' de la Agent API.",
      en: "Sonar Chat Completions is supported only until 2026-09-27. Perplexity maps it to the Agent API 'low' preset.",
    },
    apiModelId: "sonar-pro",
    openRouterId: "perplexity/sonar-pro",
    verifiedAt: VERIFIED,
    sourceUrl: SRC.perplexitySonar,
    replacementId: "perplexity-agent-low",
    selectable: false,
  },
  {
    id: "sonar",
    label: "Sonar",
    provider: "perplexity",
    target: "perplexity",
    family: "Sonar",
    status: "deprecated",
    strengths: ["search", "speed"],
    notes: {
      es: "Sonar Chat Completions tiene soporte solo hasta el 27-09-2026. Perplexity lo mapea al preset 'fast' de la Agent API.",
      en: "Sonar Chat Completions is supported only until 2026-09-27. Perplexity maps it to the Agent API 'fast' preset.",
    },
    apiModelId: "sonar",
    verifiedAt: VERIFIED,
    sourceUrl: SRC.perplexitySonar,
    replacementId: "perplexity-agent-fast",
    selectable: false,
  },
  {
    id: "sonar-reasoning-pro",
    label: "Sonar Reasoning Pro",
    provider: "perplexity",
    target: "perplexity",
    family: "Sonar",
    status: "deprecated",
    strengths: ["search", "reasoning"],
    notes: {
      es: "Sonar Chat Completions tiene soporte solo hasta el 27-09-2026. Perplexity lo mapea al preset 'medium' de la Agent API.",
      en: "Sonar Chat Completions is supported only until 2026-09-27. Perplexity maps it to the Agent API 'medium' preset.",
    },
    apiModelId: "sonar-reasoning-pro",
    openRouterId: "perplexity/sonar-reasoning-pro",
    verifiedAt: VERIFIED,
    sourceUrl: SRC.perplexitySonar,
    replacementId: "perplexity-agent-medium",
    selectable: false,
  },
  {
    id: "sonar-deep-research",
    label: "Sonar Deep Research",
    provider: "perplexity",
    target: "perplexity",
    family: "Sonar",
    status: "deprecated",
    strengths: ["search", "reasoning", "long_context"],
    notes: {
      es: "Sonar Chat Completions tiene soporte solo hasta el 27-09-2026. Perplexity lo mapea al preset 'high' de la Agent API.",
      en: "Sonar Chat Completions is supported only until 2026-09-27. Perplexity maps it to the Agent API 'high' preset.",
    },
    apiModelId: "sonar-deep-research",
    verifiedAt: VERIFIED,
    sourceUrl: SRC.perplexitySonar,
    replacementId: "perplexity-agent-high",
    selectable: false,
  },

  // ── Moonshot ──────────────────────────────────────────────────────────────
  {
    id: "kimi-k3",
    label: "Kimi K3",
    provider: "moonshot",
    target: "kimi",
    family: "Kimi",
    status: "stable",
    strengths: ["reasoning", "long_context", "multimodal", "coding"],
    notes: {
      es: "El Kimi más capaz y el que Moonshot recomienda para uso general (contexto 1M; texto, imagen y video). Siempre razona; ideal para ingeniería de software, trabajo de conocimiento y razonamiento profundo.",
      en: "The most capable Kimi and Moonshot's recommendation for general use (1M context; text, image, and video). Always reasons; built for software engineering, knowledge work, and deep reasoning.",
    },
    apiModelId: "kimi-k3",
    verifiedAt: VERIFIED,
    sourceUrl: SRC.moonshot,
    selectable: true,
    defaultForTarget: true,
    capabilities: {
      inputModalities: ["text", "image", "video"],
      outputModalities: ["text"],
      contextWindowTokens: 1048576,
      maxOutputTokens: 131072,
      latencyClass: "slow",
      structuredOutput: true,
      toolUse: true,
      nativeSearch: false,
      reasoningTier: 3,
      codingAgentFit: 3,
      taskFit: {
        chat: 2,
        coding: 3,
        codingAgent: 3,
        research: 2,
        longContext: 3,
        multimodal: 2,
        dataExtraction: 2,
        creativeWriting: 2,
        marketing: 2,
        translation: 2,
        summarization: 3,
        tutoring: 2,
        imagePrompts: 1,
        complexReasoning: 3,
        fastLightweight: 0,
      },
      promptGuidance: {
        es: "Siempre razona: reasoning_effort low, high o max (default max), y decidilo de entrada porque cambiarlo a mitad de sesión rompe el caché. La temperatura ya no se puede fijar. Separá bien material fuente de instrucciones y, para JSON, definí campos y un objeto de ejemplo.",
        en: "Always reasons: reasoning_effort low, high, or max (default max) — decide it up front, since changing it mid-session breaks caching. Temperature can no longer be set. Clearly separate source material from instructions and, for JSON, define the fields and an example object.",
      },
    },
    interactionProfiles: ["chat", "codingAgent", "multimodalAssistant"],
    promptProfile: "kimi-general",
  },
  {
    id: "kimi-k2.6",
    label: "Kimi K2.6",
    provider: "moonshot",
    target: "kimi",
    family: "Kimi",
    status: "stable",
    strengths: ["long_context", "multimodal", "writing"],
    notes: {
      es: "Kimi multimodal de uso general (texto, imagen y video; modos thinking y non-thinking). Separá fuente vs instrucciones y marcá prioridades.",
      en: "General-purpose multimodal Kimi (text, image, and video input; thinking and non-thinking modes). Split source vs instructions and mark priorities.",
    },
    apiModelId: "kimi-k2.6",
    verifiedAt: VERIFIED,
    sourceUrl: SRC.moonshot,
    selectable: true,
    capabilities: {
      inputModalities: ["text", "image", "video"],
      outputModalities: ["text"],
      contextWindowTokens: 262144,
      maxOutputTokens: null,
      latencyClass: "balanced",
      structuredOutput: true,
      toolUse: true,
      nativeSearch: false,
      reasoningTier: 2,
      codingAgentFit: 2,
      taskFit: {
        chat: 2,
        coding: 2,
        codingAgent: 2,
        research: 2,
        longContext: 2,
        multimodal: 2,
        dataExtraction: 2,
        creativeWriting: 2,
        marketing: 2,
        translation: 2,
        summarization: 2,
        tutoring: 2,
        imagePrompts: 1,
        complexReasoning: 2,
        fastLightweight: 1,
      },
      promptGuidance: {
        es: "Elegí explícitamente modo thinking o instantáneo según la tarea; la temperatura ya viene fija (1.0 thinking, 0.6 instantáneo) y no se puede cambiar. Usá Partial Mode para forzar formato, JSON Mode con campos y un ejemplo (con schemas complejos es inestable), y separá el texto fuente de las instrucciones.",
        en: "Choose thinking vs instant mode explicitly per task; temperature is now fixed (1.0 thinking, 0.6 instant) and can't be changed. Use Partial Mode to enforce format, JSON Mode with fields and an example (it is unstable with complex schemas), and split source text from instructions.",
      },
    },
    interactionProfiles: ["chat", "multimodalAssistant"],
    promptProfile: "kimi-general",
  },
  {
    id: "kimi-k2.7-code",
    label: "Kimi K2.7 Code",
    provider: "moonshot",
    target: "kimi",
    family: "Kimi",
    status: "stable",
    strengths: ["coding", "speed"],
    notes: {
      es: "Kimi especializado en coding agéntico, con seguimiento de instrucciones confiable en contextos largos. Par natural del Kimi Code CLI.",
      en: "Agentic-coding-specialized Kimi with reliable instruction following in long contexts. Natural pairing with the Kimi Code CLI.",
    },
    apiModelId: "kimi-k2.7-code",
    verifiedAt: VERIFIED,
    sourceUrl: SRC.moonshot,
    selectable: true,
    capabilities: {
      inputModalities: ["text", "image", "video"],
      outputModalities: ["text"],
      contextWindowTokens: 262144,
      maxOutputTokens: null,
      latencyClass: "balanced",
      structuredOutput: true,
      toolUse: true,
      nativeSearch: false,
      reasoningTier: 2,
      codingAgentFit: 3,
      taskFit: {
        chat: 1,
        coding: 3,
        codingAgent: 3,
        research: 1,
        longContext: 2,
        multimodal: 2,
        dataExtraction: 1,
        creativeWriting: 1,
        marketing: 1,
        translation: 1,
        summarization: 1,
        tutoring: 1,
        imagePrompts: 0,
        complexReasoning: 2,
        fastLightweight: 1,
      },
      promptGuidance: {
        es: "Tratalo como un modelo de código para loops de agente: dale contexto del repo, criterios de aceptación concretos y comandos de test, y dejalo iterar con herramientas en vez de pedirle todo de una. Devolvé el reasoning_content completo en cada turno (es obligatorio).",
        en: "Treat it as an agent-loop coding model: give repo context, concrete acceptance criteria, and test commands, and let it iterate with tools rather than one-shotting. Pass reasoning_content back in full on every turn (required).",
      },
    },
    interactionProfiles: ["codingAgent", "codeSpecialist"],
    promptProfile: "kimi-code",
  },
  {
    id: "kimi",
    label: "Kimi (legacy alias)",
    provider: "moonshot",
    target: "kimi",
    family: "Kimi",
    status: "legacy",
    strengths: ["long_context", "writing"],
    notes: {
      es: "Alias genérico legacy de Promptea (no es un id de la API de Kimi). Usá Kimi K3.",
      en: "Promptea's legacy generic alias (not a Kimi API id). Use Kimi K3.",
    },
    verifiedAt: VERIFIED,
    sourceUrl: SRC.moonshot,
    replacementId: "kimi-k3",
    selectable: false,
  },

  // ── Meta (open source) ────────────────────────────────────────────────────
  {
    id: "llama-3-70b",
    label: "Llama 3 (70B)",
    provider: "meta",
    target: "gpt",
    family: "Llama",
    status: "legacy",
    strengths: ["writing", "coding"],
    notes: {
      es: "Modelo open-source legacy que se mapeaba al target GPT. Ya no es seleccionable.",
      en: "Legacy open-source model previously mapped onto the GPT target. No longer selectable.",
    },
    verifiedAt: VERIFIED_PREV,
    sourceUrl: SRC.openai,
    replacementId: "gpt-6-sol",
    selectable: false,
  },
];

export const TARGET_GROUPS: Array<{
  target: TargetAI;
  label: string;
}> = [
  { target: "gpt", label: "GPT" },
  { target: "claude", label: "Claude" },
  { target: "gemini", label: "Gemini" },
  { target: "grok", label: "Grok" },
  { target: "kimi", label: "Kimi" },
  { target: "deepseek", label: "DeepSeek" },
  { target: "perplexity", label: "Perplexity" },
];

export function getModelById(id: string | null | undefined): ModelEntry | null {
  if (!id) return null;
  return MODEL_REGISTRY.find((m) => m.id === id) ?? null;
}

/** Models offered in the UI selector for a target (selectable only). */
export function getModelsForTarget(target: TargetAI): ModelEntry[] {
  return MODEL_REGISTRY.filter((m) => m.target === target && m.selectable);
}

/** All registry entries for a target, including legacy/deprecated. */
export function getAllModelsForTarget(target: TargetAI): ModelEntry[] {
  return MODEL_REGISTRY.filter((m) => m.target === target);
}

/** Explicit default policy: the single entry flagged defaultForTarget. */
export function defaultModelIdForTarget(target: TargetAI): string {
  const flagged = MODEL_REGISTRY.find((m) => m.target === target && m.defaultForTarget && m.selectable);
  if (flagged) return flagged.id;
  const firstSelectable = MODEL_REGISTRY.find((m) => m.target === target && m.selectable);
  return firstSelectable?.id ?? MODEL_REGISTRY.find((m) => m.target === target)?.id ?? "gpt-6-astra";
}

/**
 * Resolve a model id that may be legacy/deprecated to its current replacement.
 * Follows the replacement chain at most 3 hops to avoid cycles.
 */
export function resolveModelId(id: string | null | undefined): ModelEntry | null {
  let entry = getModelById(id);
  for (let hops = 0; entry && !entry.selectable && entry.replacementId && hops < 3; hops++) {
    entry = getModelById(entry.replacementId);
  }
  return entry;
}

export function modelNoteForTarget(target: TargetAI, lang: Lang, modelId?: string | null): string {
  const explicit = getModelById(modelId);
  if (explicit && explicit.target === target) {
    return explicit.notes[lang];
  }
  const fallback = getModelById(defaultModelIdForTarget(target));
  return fallback ? fallback.notes[lang] : "";
}

/**
 * v1.3.0: models the matcher may rank. Deprecated/legacy and non-selectable
 * entries are excluded by construction, and an entry without capability data
 * can never be recommended.
 */
export function getMatcherCandidates(): ModelEntry[] {
  return MODEL_REGISTRY.filter(
    (entry) =>
      entry.selectable &&
      (entry.status === "stable" || entry.status === "preview") &&
      entry.capabilities !== undefined
  );
}

/** Sanity export used by tests: all targets covered by the registry. */
export const REGISTRY_TARGETS = TARGETS;
